export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

// waiting for the promise to return
export const REQUEST_RESTAURANTS_PENDING = 'REQUEST_RESTAURANTS_PENDING';
export const REQUEST_RESTAURANTS_SUCCESS = 'REQUEST_RESTAURANTS_SUCCESS';
export const REQUEST_RESTAURANTS_FAILED = 'REQUEST_RESTAURANTS_FAILED';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const POST_SIGNINFO_EMAIL = 'POST_SIGNINFO_EMAIL';
export const POST_SIGNINFO_PASSWORD = 'POST_SIGNINFO_PASSWORD';
export const POST_SIGNINFO_NAME = 'POST_SIGNINFO_NAME';
