export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

// waiting for the promise to return
export const REQUEST_PEOPLE_PENDING = 'REQUEST_PEOPLE_PENDING';
export const REQUEST_PEOPLE_SUCCESS = 'REQUEST_PEOPLE_SUCCESS';
export const REQUEST_PEOPLE_FAILED = 'REQUEST_PEOPLE_FAILED';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const POST_SIGNINFO_EMAIL = 'POST_SIGNINFO_EMAIL';
export const POST_SIGNINFO_PASSWORD = 'POST_SIGNINFO_PASSWORD';
export const POST_SIGNINFO_NAME = 'POST_SIGNINFO_NAME';
